### ISSUE TITLE
[Q] Authorization (permissions) through Crossbar.io

### ISSUE THREAD

**Issue by lajosbencz** [voryx/Thruway#215]
First of all, thanks for the awesome lib!

I got stuck with the authorization model though, my environment:
Router: Crossbar compiled by PyPy
Client: AutobahnJS
Server: Thruway using PawlTransport

What I'm trying to achieve:
I'd like to use the permissions defined in .crossbar/config.json to differentiate client and server roles. For eg: only the server is allowed to register the login function, so no client can spoof it.

.crossbar/config.json:
```json
{
    "version": 2,
    "controller": {},
    "workers": [
        {
            "type": "router",
            "realms": [
                {
                    "name": "realm1",
                    "roles": [
                        {
                            "name": "server",
                            "permissions": [
                                {
                                    "uri": "",
                                    "match": "prefix",
                                    "allow": {
                                        "call": true,
                                        "register": true,
                                        "publish": true,
                                        "subscribe": true
                                    }
                                }
                            ]
                        },
                        {
                            "name": "client",
                            "permissions": [
                                {
                                    "uri": "server.auth.",
                                    "match": "prefix",
                                    "allow": {
                                        "register": false
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            "transports": "..."
        },
        {
            "type": "guest",
            "executable": "php",
            "options": {
                "workdir": "../",
                "watch": {
                    "directories": ["../"],
                    "action": "restart"
                }
            },
            "arguments": [
                "client.php"
            ]
        }
    ]
}
```

client.php:
```php
$loop = \React\EventLoop\Factory::create();
$client = new \Thruway\Peer\Client('realm1', $loop);
$client->setAuthId('server');
$client->addTransportProvider(new \Thruway\Transport\PawlTransportProvider('wss://my.router.ws'));

$client->on('open', function(\Thruway\ClientSession $session) use(&$client, &$loop, &$timer, &$di) {
    dump($client->getAuthId()); // this dumps "server" correctly
    $session->register('server.auth.login', function($args) use(&$client, &$di) {
        // do stuff
    });
});
```

```Client::getAuthId()``` returns _server_, but I still get this error in the crossbar output: ```Thruway\Transport\PawlTransportProvider 19035] Received: [8,64,1089250883591197,{},"wamp.error.not_authorized",["session is not authorized to register procedure 'server.auth.login'"]```

Any help/tips would be appreciated!

**Comment by mbonneau** [comment]
Hi @lajosbencz ,

I am not an expert on crossbar as I typically use the Thruway router.

I did get a similar setup working with crossbar using wampcra authentication.

It would be helpful to see the transports section that shows `...` because there should be some authentication configuration in there to assign users to roles. If you could post that information, that would be helpful.

Here is what I was using in the config:
```yml
                "transports": [
                {
                    "type": "web",
                    "endpoint": {
                        "type": "tcp",
                        "port": 8080
                    },
                    "paths": {
                        "/": {
                            "type": "static",
                            "directory": "../web/"
                        },
                        "ws": {
                            "type": "websocket",
                            "auth": {
                                "wampcra": {
                                    "type": "static",
                                    "users": {
                                        "joe": {
                                            "secret": "secret2",
                                            "role": "server"
                                        }
                                    }
                                },
                                "anonymous": {
                                    "type": "static",
                                    "role": "public"
                                }
                            }
                        }
                    }
                }
            ]
```
Another, more simplistic, idea would be to setup a "trusted transport" that is only bound to localhost or running on a protected port that assigns the `server` role to any client connecting there.

Let me know if this helps.
