### ISSUE TITLE
Subscriber not receiving any data with ThruwayBundle

### ISSUE THREAD

**Issue by HeliosDX** [voryx/Thruway#241]
Hi. First of all, sorry for my poor english.

I'm using the ThruwayBundle in a Symfony project.

My router is setup correctly (or so I think) since I'm able to subscribe and publish to topics using autobahn in my browser (Google Chrome) using my router and I do receive the updates when a new message is published with the console:

`session.publish('blog1', ['New article published!']);`

The problem I have is that I need a PHP based client that "pushes" a notification to the browser when a new article is published. For that, I registered an event listener called `PusherListener` as a service, like this:

```
class PusherListener {

    /** @var ClientManager */
    private $thruway_client;

    function __construct($thruway_client)
    {
        $this->thruway_client = $thruway_client;
    }

    private function publishInfo(LifecycleEventArgs $args) {
        $entity = $args->getEntity();

        if ($entity instanceof Article) {
            $this->thruway_client->publish("blog1", ["New article published"]);
        }
    }

    public function postPersist(LifecycleEventArgs $args)
    {
        $this->publishInfo($args);
    }
}
```
I put an `echo` inside the `if ($entity instanceof Article)` statement , and it works, so I think the problem comes from this line:

`$this->thruway_client->publish("blog1", ["New article published"]);`

But with this method,the console on my router is empty...

 Am I doing something wrong?

**Comment by davidwdan** [comment]
@HeliosDX how are you injecting `$thruway_client`?

**Comment by HeliosDX** [comment]
@davidwdan My bad, I forgot the `services.yml` file:

```
notif_new_article.listener:
     class: Helios\BlogBundle\EventListener\PusherListener
     arguments: ['@thruway.client']
     tags:
         - { name: doctrine.event_listener, event: postPersist }
```
